openapi: 3.0.0
info:
  version: '1.0'
  title: "pit-jv-lambda-examples"
  description: POC API
  license:
    name: MIT

x-amazon-apigateway-request-validators:
  Validate body:
    validateRequestParameters: false
    validateRequestBody: true
  params:
    validateRequestParameters: true
    validateRequestBody: false
  Validate body, query string parameters, and headers:
    validateRequestParameters: true
    validateRequestBody: true

paths:
  /open:
    options:
      x-amazon-apigateway-integration:
        type: mock
        requestTemplates:
          application/json: |
            {
              "statusCode" : 200
            }
        responses:
          "default":
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Headers:
                Fn::Sub: ${CorsHeaders}
              method.response.header.Access-Control-Allow-Methods:
                Fn::Sub: ${CorsMethods}
              method.response.header.Access-Control-Allow-Origin:
                Fn::Sub: ${CorsOrigin}
            responseTemplates:
              application/json: |
                {}
      responses:
        200:
          $ref: '#/components/responses/200Cors'
    get:
      security:
      - api_key: []      
      x-amazon-apigateway-integration:
        credentials:
          Fn::GetAtt: [ ApiGatewayLambdaRole, Arn ]
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${OpenLambdaFunction.Arn}/invocations
        httpMethod: POST
        type: aws
        responses:
          default:
            statusCode: 200
          ".*MISSING_AUTHENTICATION_TOKEN.*":
            statusCode: 403
            responseTemplates:
              application/json: $input.path('$.errorMessage')
          ".*NOT_FOUND.*":
            statusCode: 404
            responseTemplates:
              application/json: $input.path('$.errorMessage')
#        requestTemplates:
#          application/json:
#            Fn::Sub: |-
#              #set($inputRoot = $input.path('$'))
#              {
#                "message": "$inputRoot.message",
#                "url": "$inputRoot.url"
#              }
      summary: Consume body info and send sms
      responses:
        200:
          $ref: '#/components/responses/200Empty'
        403:
          $ref: '#/components/responses/Error'
        404:
          $ref: '#/components/responses/Error'
  /:
    options:
      x-amazon-apigateway-integration:
        type: mock
        requestTemplates:
          application/json: |
            {
              "statusCode" : 200
            }
        responses:
          "default":
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Headers:
                Fn::Sub: ${CorsHeaders}
              method.response.header.Access-Control-Allow-Methods:
                Fn::Sub: ${CorsMethods}
              method.response.header.Access-Control-Allow-Origin:
                Fn::Sub: ${CorsOrigin}
            responseTemplates:
              application/json: |
                {}
      responses:
        200:
          $ref: '#/components/responses/200Cors'
    post:
      security:
      - api_key: []
      - TestCognitoAuthorizer: []
      x-amazon-apigateway-integration:
        credentials:
          Fn::GetAtt: [ ApiGatewayLambdaRole, Arn ]
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaFunction.Arn}/invocations
        httpMethod: POST
        type: aws
        responses:
          default:
            statusCode: 200
          ".*MISSING_AUTHENTICATION_TOKEN.*":
            statusCode: 403
            responseTemplates:
              application/json: $input.path('$.errorMessage')
          ".*NOT_FOUND.*":
            statusCode: 404
            responseTemplates:
              application/json: $input.path('$.errorMessage')
        requestTemplates:
          application/json:
            Fn::Sub: |-
              #set($inputRoot = $input.path('$'))
              {
                "message": "$inputRoot.message"
              }
      summary: Consume body info and delete topic
      responses:
        200:
          $ref: '#/components/responses/200Empty'
        403:
          $ref: '#/components/responses/Error'
        404:
          $ref: '#/components/responses/Error'

components:
  securitySchemes:
    api_key:
      type: "apiKey"
      name: "x-api-key"
      in: "header"
    TestCognitoAuthorizer:
      type: "apikey"
      name: "Authorization"
      in: "header"
      x-amazon-apigateway-authtype: "cognito_user_pools"
      x-amazon-apigateway-authorizer:
        name: TestCognitoAuthorizer
        type: "cognito_user_pools"
#        providerARNs:
#        - "arn:aws:cognito-idp:{region}:{account_id}:userpool/{user_pool_id}"
        providerARNs:
          - Fn::Sub: arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${UserPool.Arn}
        identitySource: method.request.header.Authorization

  schemas:
    Error:
      title: Error
      type: object
      properties:
        code:
          type: string
        message:
          type: string

  responses:
    200Empty:
      description: Default OK response

    200Cors:
      description: Default response for CORS method
      headers:
        Access-Control-Allow-Headers:
          schema:
            type: "string"
        Access-Control-Allow-Methods:
          schema:
            type: "string"
        Access-Control-Allow-Origin:
          schema:
            type: "string"

    Error:
      description: Error Response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
      headers:
        Access-Control-Allow-Headers:
          schema:
            type: "string"
        Access-Control-Allow-Origin:
          schema:
            type: "string" 